[package]
name = "infini-rt"
version = "0.0.0"
edition = "2021"
authors = ["YdrMaster <ydrml@hotmail.com>"]

[build-dependencies]
build-script-cfg.workspace = true
bindgen.workspace = true
search-infini-tools.workspace = true
