[package]
name = "infini-op"
version = "0.0.0"
edition = "2021"
authors = ["YdrMaster <ydrml@hotmail.com>"]

[dependencies]
digit-layout = "0.2"

[build-dependencies]
build-script-cfg.workspace = true
bindgen.workspace = true
search-infini-tools.workspace = true
